version: '3'
services:
  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - ${PWD}/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    ports:
    - "6379:6379"
    
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    # - REDIS_HOSTS=redis_server:redis:6379:redis:123456
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - REDIS_PASSWORD=123456
    ports:
    - "8081:8081"